name: Sync README and images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy docs content
        run: |
          cp -f -a /docs/. ${{ runner.temp }}/.

      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: docs

      - name: Commit and push documentation
        run: |
          rm -r ${{ runner.temp }}/*
          cp -f -a ${{ runner.temp }}/. .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit --signoff -m "Sync documentation from main"
          git push