name: Sync documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
      - vars/**

jobs:
  sync-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Documentation with Gradle
        run: ./gradlew task documentation

      - name: Copy docs content
        run: |
          cp -f -a /docs/. ${{ runner.temp }}/.

      - name: Checkout GitHub Pages branch
        uses: actions/checkout@v2
        with:
          ref: docs

      - name: Commit and push documentation
        run: |
          rm -r *
          cp -f -a ${{ runner.temp }}/. .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit --signoff -m "Sync documentation from main"
          git push